#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Unire_Android.Resource", IsApplication=true)]

namespace Unire_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int iconB = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int iconG = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int iconO = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int iconR = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int iconY = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int monoandroidsplash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int noti_blue = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int noti_green = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int noti_orange = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int noti_purple = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int noti_red = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int noti_yellow = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int splash = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int Blue = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int Green = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int Orange = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int Purple = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int Red = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int Yellow = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int imageButton2 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int imageButton3 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int imageButton4 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int imageButton5 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int imageButton6 = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout1 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int ov = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Blue = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Green = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Menu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Orange = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Purple = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Red = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Yellow = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int Blue = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int Green = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int Orange = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int Purple = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Red = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Yellow = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Mono_Android_Theme_Splash = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
